"""Public package metadata and core API surface for KVScope."""

__version__ = "0.1.0"

from kvscope.api import (
    aggregate_memory_requirements,
    analyze_memory_constraints,
    assess_memory_feasibility,
    estimate_hardware_memory_budget,
    estimate_kv_cache,
    estimate_runtime_overhead,
    estimate_weight_memory,
    evaluate_memory_feasibility,
    resolve_backend_profile,
    resolve_hardware_profile,
    resolve_model,
)
from kvscope.domain import (
    BackendProfile,
    ByteRange,
    ConstraintAnalysis,
    ConstraintPolicy,
    FeasibilityResult,
    HardwareMemoryBudget,
    HardwareProfile,
    InternalFeasibilityStatus,
    MemoryAggregationResult,
    MemoryFeasibilityReport,
    ModelSource,
    ModelSpec,
    ProductFeasibilityStatus,
    RatioRange,
    ResolvedModel,
    RuntimeOverheadEstimate,
    RuntimeOverheadOverrides,
    SignedByteRange,
)
from kvscope.resolvers import ResolvedBackendProfile, ResolvedHardwareProfile

__all__ = [
    "BackendProfile",
    "ByteRange",
    "ConstraintAnalysis",
    "ConstraintPolicy",
    "FeasibilityResult",
    "HardwareMemoryBudget",
    "HardwareProfile",
    "InternalFeasibilityStatus",
    "MemoryAggregationResult",
    "MemoryFeasibilityReport",
    "ModelSource",
    "ModelSpec",
    "ProductFeasibilityStatus",
    "RatioRange",
    "ResolvedBackendProfile",
    "ResolvedHardwareProfile",
    "ResolvedModel",
    "RuntimeOverheadEstimate",
    "RuntimeOverheadOverrides",
    "SignedByteRange",
    "__version__",
    "aggregate_memory_requirements",
    "analyze_memory_constraints",
    "assess_memory_feasibility",
    "estimate_hardware_memory_budget",
    "estimate_kv_cache",
    "estimate_runtime_overhead",
    "estimate_weight_memory",
    "evaluate_memory_feasibility",
    "resolve_backend_profile",
    "resolve_hardware_profile",
    "resolve_model",
]
